class AppImages {
  get firstOnBoardingImage => 'assets/images/firstonboardingimage.png';
  get secondOnBoardingImage => 'assets/images/secondonboardingimage.png';
  get thirdOnBoardingImage => 'assets/images/thirdonboardingimage.png';
  get fourthOnBoardingImage => 'assets/images/fourthonboardingimage.png';
  get loginImage => 'assets/images/loginimage.png';
  get studentLogin => "assets/images/studentlogin.png";
  get parentLogin => "assets/images/parentlogin.png";
  get mentorLogin => "assets/images/mentorlogin.png";
  get firstStudentOnBoardingImage => 'assets/images/firststudentonboarding.png';
  get secondStudentOnBoardingImage => 'assets/images/secondstudentonboarding.png';
  get fourthStudentOnBoardingImage => 'assets/images/fourthstudentonboarding.png';
  get studentSignUpImage => 'assets/images/signupstudent.png';
  get firstParentOnBoardingImage => 'assets/images/firstparentonboarding.png';
  get secondParentOnBoardingImage => 'assets/images/secondparentonboarding.png';
  get thirdParentOnBoardingImage => 'assets/images/thirdparentonboarding.png';
  get fourthParentOnBoardingImage => 'assets/images/fourthparentonboarding.png';
  get fifthParentOnBoardingImage => 'assets/images/fifthparentonboarding.png';
  get parentSignUpImage => 'assets/images/parentsignupimage.png';
  get firstMentorOnBoardingImage => 'assets/images/firstmentoronboardingimage.png';
  get mentorSignUpImage => 'assets/images/mentorsignupimage.png';
  get appIcon => 'assets/images/Vroar Icon.png';
  get imageGalleryIcon => 'assets/icons/imageGalleryIcon.png';
  get cameraIcon => 'assets/icons/cameraIcon.png';
  get avatar => 'assets/images/avatar.jpg';
  get parentStrengthBackground => 'assets/images/parentStrengthBackground.png';
  get sunIcon => 'assets/icons/sunEmoji.png';
  get roadMap => 'assets/icons/Roadmap.png';
  get home => 'assets/icons/home.png';
  get jhony => 'assets/images/jhonyImage.png';
  get abram => 'assets/images/abram.png';
  get alex => 'assets/images/alex.png';
  get mentorImage => 'assets/images/mentorImage.png';
  get sendIcon => 'assets/icons/sendIcon.png';
  get notificationIcon => 'assets/icons/notification.png';
  get messageBackground => 'assets/images/messageBackground.png';
  get parentAvatar => 'assets/images/Parents.jpg';
  get internshipImage => 'assets/images/internshipImage.png';
  get mentorAvatar => 'assets/images/Company.jpg';
  get thompson => 'assets/images/thompson.png';
  get maskGroup => 'assets/icons/Maskgroup.png';
  get logo => 'assets/images/VroarIconPng.png';
  get videoIcon => 'assets/icons/VideoIcon.png';
  get calender => 'assets/icons/calender.png';
  get myTrekLogo => 'assets/images/MyTreks_AppIcon.png';
  get noInternet => 'assets/images/noInternet.png';

  get assessmentBackground => 'assets/icons/AssessmentBackground.png';
  get flag => 'assets/icons/Flag.png';
  get moonIcon => 'assets/icons/moon.png';
  get starBadge => 'assets/icons/StarBadge.png';
  get industryLarge => 'assets/icons/industry_large.png';

  //All SVG BottomNavigation Icons
  get coursesSvg => 'assets/svgIcons/courses.svg';
  get coursesSvgActive => 'assets/svgIcons/coursesActive.svg';
  get coinSvg => 'assets/svgIcons/Coins.svg';
  get coinSvgActive => 'assets/svgIcons/coinsActive.svg';
  get homeSvg => 'assets/svgIcons/Home.svg';
  get homeSvgActive => 'assets/svgIcons/HomeActive.svg';
  get profileSvg => 'assets/svgIcons/Profile.svg';
  get profileSvgActive => 'assets/svgIcons/ProfileActive.svg';
  get mapSvg => 'assets/svgIcons/mapIcon.svg';
  get mapSvgActive => 'assets/svgIcons/mapIconActive.svg';
  get defaultCompanylogo => 'assets/images/default_company_logo.jpg';

  // All SVG Icons
  get fileBlackIcon => 'assets/svgIcons/fileBlackIcon.svg';
  get profileIconDark => 'assets/svgIcons/profileIconDark.svg';
  get subscription => 'assets/svgIcons/subscription.svg';
  get callIcon => 'assets/svgIcons/callIcon.svg';
  get ticket => 'assets/svgIcons/ticket.svg';
  get logoutIcon => 'assets/svgIcons/logoutIcon.svg';
  get editIcon => 'assets/svgIcons/editIcon.svg';
  get msg => 'assets/svgIcons/msg.svg';
  get bagBanner => 'assets/svgIcons/bagBanner.svg';
  get boxStarIcon => 'assets/svgIcons/boxStarIcon.svg';
  get flagIcon => 'assets/svgIcons/flagIcon.svg';
  get bigCoins => 'assets/svgIcons/BigCoins.svg';
  get webinar => 'assets/svgIcons/Webinar.svg';
  get onFieldWorkshop => 'assets/svgIcons/OnFieldWorkshop.svg';
  get mentorSession => 'assets/svgIcons/mentorSession.svg';
  get logoutImage => 'assets/svgIcons/logoutImage.svg';
  get timer => 'assets/svgIcons/timer.svg';
  get money => 'assets/svgIcons/money.svg';
  get documentSummary => 'assets/svgIcons/document_summary.svg';
  get description => 'assets/svgIcons/description.svg';
  get circleTick => 'assets/svgIcons/circle_tick.svg';
  get vectorRight => "assets/svgIcons/vectorright.svg";
  get vectorLeft => "assets/svgIcons/vectorleft.svg";
  get googleIcon => 'assets/svgIcons/googleicon.svg';
  get appleIcon => "assets/svgIcons/appleicon.svg";
  get experienceIcon2 => 'assets/svgIcons/experienceIcon2.svg';
  get academicIcon => 'assets/svgIcons/Academic.svg';
  get skillsIcon => 'assets/svgIcons/Skills.svg';
  get topicsIcon => 'assets/svgIcons/Topics.svg';
  get careerIcon => 'assets/svgIcons/Career.svg';
  get achievementsIcon => 'assets/svgIcons/Achievements.svg';
  get officeIcon => 'assets/svgIcons/officeIcon.svg';
  get experienceIcon => 'assets/svgIcons/experienceIcon.svg';
  get deleteIcon => 'assets/svgIcons/deleteIcon.svg';
  get congratulations => 'assets/svgIcons/Congratulations.svg';
  get successIcon => 'assets/svgIcons/successIcon.svg';
  get successIconFull => 'assets/svgIcons/successIconFull.svg';
  get lockFullIcon => 'assets/svgIcons/lockFullIcon.svg';
  get bellIcons => 'assets/svgIcons/bellIcon.svg';
  get playIcon => 'assets/svgIcons/playIcon.svg';
  get schoolIcon => 'assets/svgIcons/schoolIcon.svg';
  get document => 'assets/svgIcons/document.svg';
  get errorIcon => 'assets/svgIcons/circle_exclamation_mark.svg';
  get degreeRoll => 'assets/svgIcons/DegreeRoll.svg';
  get bagIcon => 'assets/svgIcons/BagIcon.svg';
  get copy => 'assets/svgIcons/copy.svg';
  get roadMapCareerIcon => 'assets/svgIcons/career_logo.svg';
  get roadMapIndustryIcon => 'assets/svgIcons/industry_large.svg';
  get roadMapStrengthIcon => 'assets/svgIcons/strength_large.svg';
  get roadMapBottleIcon => 'assets/svgIcons/bottle.svg';
  get roadMapNewTrackerIcon => 'assets/svgIcons/tracker_1.svg';
  get videoTitle => 'assets/svgIcons/video_title.svg';
  get youtubeVideoTitle => 'assets/svgIcons/youtube_video_title.svg';
  get quizTitle => 'assets/svgIcons/QuizTitle.svg';
  get articleTitle => 'assets/svgIcons/article_title.svg';
  get journalTitle => 'assets/svgIcons/journal_title.svg';
  get inHouseVideoTitle => 'assets/svgIcons/video_title.svg';
  get introductionVideo => 'assets/svgIcons/IntroductionVideo.svg';
  get assessment => 'assets/svgIcons/Assessment.svg';
  get assignment => 'assets/svgIcons/Assignment.svg';
  get introspect => 'assets/svgIcons/Introspect.svg';
  get assessmentOnboarding => 'assets/svgIcons/assessmentOnboarding.svg';
  get strengthCoaching => 'assets/svgIcons/strengthCoaching.svg';
  get emptyWallet => 'assets/svgIcons/walletEmpty.svg';
  get handLeft => 'assets/svgIcons/handLeft.svg';
  get handRight => 'assets/svgIcons/handRight.svg';

  // roadmap images
  get roadMapMainImage => 'assets/images/roadmap_bg.png';
  get roadMapSnowBGImage => 'assets/images/roadmap_snow_bg.png';
  get roadMapDesertBGImage => 'assets/images/roadmap_desert_theme.jpg';
  get roadMapLavaBGImage => 'assets/images/roadmap_lawa_theme.jpg';
  get roadMapSnowBG2Image => 'assets/images/roadmap_snow_bg_2.png';
  get roadMapUnderWaterBGImage => 'assets/images/roadmap_underwater_theme.jpg';
  get roadMapDesertBG2Image => 'assets/images/roadmap_desert_theme_2.jpg';
  get roadMapLavaBG2Image => 'assets/images/roadmap_lawa_theme_2.jpg';
  get roadMapDemoImage => 'assets/images/roadmap_demo.png';
  get roadMapDemo2Image => 'assets/images/roadmap_bg (1).png';
  get roadMapCoinIcon => 'assets/icons/coin_logo.png';
  get roadMapTileBlue => 'assets/icons/blue_tile.png';
  get roadMapTileGreenCheckMark => 'assets/icons/greenCheck.png';
  get roadMapLockIcon => 'assets/icons/lockIcon.png';
  get roadMapTrackerIcon => 'assets/icons/tracker.png';
  get roadMapFileIcon => 'assets/icons/file.png';
  get roadMapFireIcon => 'assets/icons/fire.png';
  get roadMapFullScreenViewIcon => 'assets/icons/full_screen_view.png';
  get roadMapExitFullScreenIcon => 'assets/icons/exit_full_screen.png';

  // roadmap ends here

  // lottie images
  get dayStreaks3 => 'assets/lottie/dayStreaks.json';
  get articleCompleted => 'assets/lottie/Article_Completed.json';
  get article => 'assets/lottie/Article.json';
  get assessmentCompleted => 'assets/lottie/Assessment_Completed.json';
  get assessmentLottie => 'assets/lottie/Assessment.json';
  get cloudTransition => 'assets/lottie/Cloud_transition.json';
  get coinAnimation => 'assets/lottie/Coinanimation.json';
  get inHouseVideoCompleted => 'assets/lottie/InHouseVideoCompleted.json';
  get inHouseVideo => 'assets/lottie/InHouseVideo.json';
  get journalCompleted => 'assets/lottie/JournalCompleted.json';
  get journal => 'assets/lottie/Journal.json';
  get levelComplete => 'assets/lottie/LevelComplete.json';
  get presentationIcon => 'assets/lottie/PresentationIcon.json';
  get quizCompleted => 'assets/lottie/QuizCompleted.json';
  get quiz => 'assets/lottie/Quiz.json';
  get roadmapCompleted => 'assets/lottie/RoadmapCompleted.json';
  get sandClockLoading => 'assets/lottie/SandClockLoading.json';
  get tickAnimation => 'assets/lottie/TickAnimation.json';
  get trophy => 'assets/lottie/Trophy.json';
  get flagLottie => 'assets/lottie/Halfway.json';
  get unlock => 'assets/lottie/Unlock.json';
  get youtubeVideoCompleted => 'assets/lottie/YoutubeVideoCompleted.json';
  get youtubeVideo => 'assets/lottie/YoutubeVideo.json';
  get noData => 'assets/lottie/noData.json';
  get dataNotFound => 'assets/lottie/dataNotFound.json';

  static final AppImages _appImages = AppImages._internal();
  factory AppImages() {
    return _appImages;
  }
  AppImages._internal();
}

AppImages appImages = AppImages();
