// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALhRS8Gr22CRiBA9OzxK6zoDXd0z50XvI',
    appId: '1:814443057039:web:57c7308337de3dc4d585fa',
    messagingSenderId: '814443057039',
    projectId: 'vroar-188a2',
    authDomain: 'vroar-188a2.firebaseapp.com',
    storageBucket: 'vroar-188a2.appspot.com',
    measurementId: 'G-LNDT7MESRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIhfGX6yKUe8r-IAz6zhiWwwiHQE9_L-E',
    appId: '1:814443057039:android:267f1339fb9b6682d585fa',
    messagingSenderId: '814443057039',
    projectId: 'vroar-188a2',
    storageBucket: 'vroar-188a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYGIpuURvnZc7tEqj-0PStzdLwCWbglpI',
    appId: '1:814443057039:ios:6a1c9541414cd84cd585fa',
    messagingSenderId: '814443057039',
    projectId: 'vroar-188a2',
    storageBucket: 'vroar-188a2.appspot.com',
    iosBundleId: 'com.vroar.vroar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYGIpuURvnZc7tEqj-0PStzdLwCWbglpI',
    appId: '1:814443057039:ios:6a1c9541414cd84cd585fa',
    messagingSenderId: '814443057039',
    projectId: 'vroar-188a2',
    storageBucket: 'vroar-188a2.appspot.com',
    iosBundleId: 'com.vroar.vroar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALhRS8Gr22CRiBA9OzxK6zoDXd0z50XvI',
    appId: '1:814443057039:web:db3b6ae545adf430d585fa',
    messagingSenderId: '814443057039',
    projectId: 'vroar-188a2',
    authDomain: 'vroar-188a2.firebaseapp.com',
    storageBucket: 'vroar-188a2.appspot.com',
    measurementId: 'G-91DXK68NZ3',
  );

}
